FROM python:3.9-slim

WORKDIR /app

# Installer les dépendances
COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code de l'application
COPY . .

# Exposer le port Streamlit
EXPOSE 8501

# Commande pour démarrer Streamlit
#CMD ["streamlit", "run", "app.py"]
