#Mention the base image 
FROM python:3.11-slim

#Set current working directory
WORKDIR /app

#Install the required libraries
COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

#Copy the current folder structure and content to docker folder
COPY . /app

#Expose the port within docker 
EXPOSE 5050

#container start up command
#CMD ["python", "flask_api.py"]